# Generated by Django 4.2.3 on 2024-03-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
