# Generated by Django 5.0.3 on 2024-08-14 01:17

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('ready_to_send', models.BooleanField(default=False, verbose_name='آماده برای ارسال')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.CreateModel(
            name='Shiping_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiping_price', models.PositiveIntegerField(default=45000)),
            ],
            options={
                'verbose_name': 'تغییر هزینه پست و بسته بندی',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number :')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name :')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name :')),
                ('city', models.CharField(max_length=50, verbose_name='city :')),
                ('address', models.CharField(max_length=150, verbose_name='address :')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code :')),
                ('datetime_order', models.DateTimeField(auto_now_add=True)),
                ('datetime_order_modified', models.DateTimeField(auto_now=True)),
                ('peyment_status', models.BooleanField(default=False, verbose_name='peyment_status :')),
                ('order_status', models.CharField(choices=[('در انتظار تایید', 'در انتظار تایید'), ('در حال آماده سازی', 'در حال آماده سازی'), ('ارسال شده', 'ارسال شده')], default='در انتظار تایید', max_length=50, null=True, verbose_name='order_status :')),
                ('order_note', models.TextField(blank=True, verbose_name='Do You Have Any Note For This Order?')),
                ('total_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='total order price:')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=225, verbose_name=' zarinpal authority code:')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='customer :')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.province', verbose_name='province :')),
            ],
            options={
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='products.product')),
            ],
        ),
    ]
