# Generated by Django 4.2.3 on 2024-02-23 08:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('birht_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name :')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name :')),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=10)),
                ('datetime_order', models.DateField(auto_now_add=True)),
                ('datetime_order_modified', models.DateField(auto_now=True)),
                ('peyment_status', models.CharField(choices=[('cancel', 'Cancel'), ('waiting', 'Waiting'), ('peyed', 'Peyed')], default='waiting', max_length=50, null=True)),
                ('order_status', models.CharField(choices=[('confirming', 'Confirming'), ('processing', 'Processing'), ('posted', 'Poested')], default='confirming', max_length=50, null=True)),
                ('order_note', models.TextField(blank=True, verbose_name='Do You Have Any Note For This Order?')),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
