# Generated by Django 4.2.3 on 2024-02-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_zarinpal_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime_order_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
