# Generated by Django 4.2.3 on 2024-03-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shiping_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiping_price', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
