# Generated by Django 4.2.3 on 2024-03-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_shiping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiping_price',
            name='shiping_price',
            field=models.PositiveIntegerField(default=45000),
        ),
    ]
