# Generated by Django 4.2.3 on 2024-03-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'مشتری ها'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('در انتظار تایید', 'در انتظار تایید'), ('در حال آماده سازی', 'در حال آماده سازی'), ('ارسال شده', 'ارسال شده')], default='confirming', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='peyment_status',
            field=models.CharField(choices=[('لغو شده', 'لغو شده'), ('در انتظار', 'در انتظار'), ('پرداخت شده', 'پرداخت شده')], default='waiting', max_length=50, null=True),
        ),
    ]
