# Generated by Django 4.2.3 on 2024-03-31 01:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_customer_options_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('در انتظار تایید', 'در انتظار تایید'), ('در حال آماده سازی', 'در حال آماده سازی'), ('ارسال شده', 'ارسال شده')], default='confirming', max_length=50, null=True, verbose_name='order_status :'),
        ),
        migrations.AlterField(
            model_name='order',
            name='peyment_status',
            field=models.CharField(choices=[('لغو شده', 'لغو شده'), ('در انتظار', 'در انتظار'), ('پرداخت شده', 'پرداخت شده')], default='waiting', max_length=50, null=True, verbose_name='peyment_status :'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number :'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='total order price:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zarinpal_authority',
            field=models.CharField(blank=True, max_length=225, verbose_name=' zarinpal authority code:'),
        ),
    ]
