# Generated by Django 4.2.3 on 2024-04-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_status_alter_order_peyment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code :'),
        ),
    ]
