# Generated by Django 4.2.3 on 2024-04-08 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_wishlist_customer_wishlist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_alter_order_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='customer :'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
