# Generated by Django 4.2.3 on 2024-04-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_customer_order_user_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='peyment_status',
            field=models.CharField(choices=[('لغو شده', 'لغو شده'), ('در انتظار تایید', 'در انتظار تایید'), ('پرداخت شده', 'پرداخت شده')], default='waiting', max_length=50, null=True, verbose_name='peyment_status :'),
        ),
    ]
