# Generated by Django 5.0.3 on 2024-08-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='number :'),
        ),
    ]
