# Generated by Django 4.2.3 on 2024-02-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_property_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='poster',
        ),
    ]
