# Generated by Django 4.2.3 on 2024-02-26 04:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
