# Generated by Django 4.2.3 on 2024-03-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_color_color1_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide_img')),
                ('title', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name_plural': 'اسلاید های صفحه اصلی',
            },
        ),
    ]
