# Generated by Django 4.2.3 on 2024-03-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'تخفیف ها'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'تصاویر محصولات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'محصولات'},
        ),
    ]
