# Generated by Django 4.2.3 on 2024-04-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_slide_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='products.category'),
        ),
    ]
